apiVersion: apps/v1
kind: Deployment
metadata:
  name: kpt-tech
  namespace: default
  labels:
    app: dry-run
spec:
  selector:
    matchLabels:
      app: dry-run
  template:
    metadata:
      labels:
        app: dry-run
    spec:
      containers:
        - name: kpt-tech
          image: us-central1-docker.pkg.dev/adroit-nimbus-370411/kpt-tech/kpt:1.0
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
          livenessProbe:
            httpGet:
              port: 8080
              path: /
          readinessProbe:
            httpGet:
              port: 8080
              path: /
