apiVersion: apps/v1
kind: Deployment
metadata:
  name: kpt
  namespace: tech-session
  labels:
    app: kpt
spec:
  selector:
    matchLabels:
      app: kpt
  template:
    metadata:
      labels:
        app: kpt
    spec:
      containers:
        - name: kpt
          image: us-central1-docker.pkg.dev/adroit-nimbus-370411/tech-repo/kpt:2.0
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
          livenessProbe:
            httpGet:
              port: 8080
              path: /
          readinessProbe:
            httpGet:
              port: 8080
              path: /
