apiVersion: fn.kpt.dev/v1alpha1
kind: ApplyReplacements
metadata:
  name: replacements-fn-config
replacements:
  - source:
      name: kpt
      kind: Deployment
      fieldPath: spec.template.spec
    targets:
      - fieldPaths:
          - spec.template.spec
        options:
          create: true
        select:
          name: kpt-tech
          kind: Deployment
